name: .NET Core

on: [push]

jobs:
  build:
    strategy:
      matrix:
        runs-on: [ubuntu-latest, windows-latest]

    name: Running tests on ${{ matrix.runs-on }}. 
    steps:
    - uses: actions/checkout@master
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Build with dotnet
      run: dotnet build --configuration Release
